#!/bin/bash
#set -Ceu
#-----------------------------------------------------------------------------
# bashのシェル変数（全95個）
# 作成日時: 2019-04-06T14:56:33+0900
# http://ytyaru.hatenablog.com/entry/2020/06/16/000000
#-----------------------------------------------------------------------------
ShowParams() {
	# 引数で変数名を指定して参照したかったができない。配列、連想配列は不可。
	local -r VNAME="$1"
	echo "ParamNum: $#"
	local count=1
	echo '------------------------'
	echo "${1}"
	echo "${!1}"
	echo "${!VNAME}"
	echo "${!VNAME[@]}"
	#echo "${!VNAME[#]}"
	echo "${!VNAME[*]}"
	#echo "${!#VNAME}"
	#echo "${#!VNAME[@]}"
	#echo "${#${!VNAME}[@]}"
	echo '------------------------'
	for ((i=0; i<10; i++)); do echo "${i}: ${!VNAME[$i]}"; done;
	#for p in $@; do echo "$count: $p"; ((count++)); done;
}
#ShowNamedParams() {
#	echo "ParamNum: $#"
#	local count=1
#	#for key in "${!1[@]}"; echo "${key}: ${!1[$key]}"; done;
#	#for key in $(eval echo "${!'"$1"'}[@]"); echo "${key}: ""$(eval echo ${$1[$key]})"; done;
#	#for key in $(eval "${!'"$1"'}[@]"); echo "${key}: ""$(eval ${$1[$key]})"; done;
#}
Run() {
	echo "$BASH"
	echo "$BASHOPTS"
	echo "$BASHPID"
	echo "$BASH_ALIASES"
	echo "$BASH_ARGC"
	echo "$BASH_ARGV"
	echo "$BASH_CMDS"
	echo "$BASH_COMMAND"
	echo "$BASH_EXECUTION_STRING"
	echo "$BASH_LINENO"
	echo "$BASH_REMATCH"
	echo "$BASH_SOURCE"
	echo "$BASH_SUBSHELL"
	echo "$BASH_VERSINFO"
	ShowParams "BASH_VERSINFO"
	echo "${BASH_VERSINFO[0]}"
	echo "${BASH_VERSINFO[1]}"
	echo "${BASH_VERSINFO[2]}"
	echo "${BASH_VERSINFO[3]}"
	echo "${BASH_VERSINFO[4]}"
	echo "${BASH_VERSINFO[5]}"
	echo "$BASH_VERSION"
	echo "$COMP_CWORD"
	echo "$COMP_KEY"
	echo "$COMP_LINE"
	echo "$COMP_POINT"
	echo "$COMP_TYPE"
	echo "$COMP_WORDBREAKS"
	echo "$COMP_WORDS"
	echo "$COPROC"
	echo "$DIRSTACK"
	echo "$EUID"
	echo "$FUNCNAME"
	echo "$GROUPS"
	echo "$HISTCMD"
	echo "$HOSTNAME"
	echo "$HOSTTYPE"
	echo "$LINENO"
	echo "$MACHTYPE"
	echo "$MAPFILE"
	echo "$OLDPWD"
	echo "$OPTARG"
	echo "$OPTIND"
	echo "$OSTYPE"
	echo "$PIPESTATUS"
	echo "$PPID"
	echo "$PWD"
	echo "$RANDOM"
	echo "$READLINE_LINE"
	echo "$READLINE_POINT"
	echo "$REPLY"
	echo "$SECONDS"
	echo "$SHELLOPTS"
	echo "$SHLVL"
	echo "$UID"

	echo "$BASH_ENV"
	echo "$BASH_XTRACEFD"
	echo "$CDPATH"
	echo "$COLUMNS"
	echo "$COMPREPLY"
	echo "$EMACS"
	echo "$ENV"
	echo "$FCEDIT"
	echo "$FIGNORE"
	echo "$FUNCNEST"
	echo "$GLOBIGNORE"
	echo "$HISTCONTROL"
	echo "$HISTFILE"
	echo "$HISTFILESIZE"
	echo "$HISTIGNORE"
	echo "$HISTSIZE"
	echo "$HISTTIMEFORMAT"
	echo "$HOME"
	echo "$HOSTFILE"
	echo "$IFS"
	echo "$IGNOREEOF"
	echo "$INPUTRC"
	echo "$LANG"
	echo "$LC_ALL"
	echo "$LC_COLLATE"
	echo "$LC_CTYPE"
	echo "$LC_MESSAGES"
	echo "$LC_NUMERIC"
	echo "$LINES"
	echo "$MAIL"
	echo "$MAILCHECK"
	echo "$MAILPATH"
	echo "$MAILPATH"
	echo "$OPTERR"
	echo "$PATH"
	echo "$POSIXLY_CORRECT"
	echo "$PROMPT_COMMAND"
	echo "$PROMPT_DIRTRIM"
	echo "$PS1"
	echo "$PS2"
	echo "$PS3"
	echo "$PS4"
	echo "$SHELL"
	echo "$TIMEFORMAT"
	echo "$TMOUT"
	echo "$TMPDIR"
	echo "$auto_resume"
	echo "$histchars"
}
Run
